# Generated by Django 4.2.1 on 2023-11-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='country',
        ),
    ]
