# Generated by Django 4.2.6 on 2023-12-24 12:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dwelling',
            options={'ordering': ['rating', '-price'], 'verbose_name': 'Dwellings', 'verbose_name_plural': 'Dwellings'},
        ),
        migrations.AddField(
            model_name='dwelling',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dwelling',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dwelling',
            name='total_reviews',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dwelling',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dwellings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occupieddate',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupieddates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dwelling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.dwelling')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('dwelling', 'user')},
            },
        ),
    ]
