# Generated by Django 4.2.6 on 2023-12-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dwelling_options_dwelling_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
